Add compatibility mode for Firefox
crxjs/chrome-extension-tools pull request #644
Opened 2023-02-02 00:41 UTC by laptou

I wanted to be able to use this extension to create MV3 extensions for both Chrome and Firefox. They each implement MV3 a little differently; in particular:
- Firefox does not allow `use_dynamic_url` in `web_accessible_resources` because it the resource URLs in Firefox are always dynamic
- Firefox continues to use background pages instead of service workers

So I added a new config option called `browser` that can be either `"firefox"`  or `"chrome"`, and if it is `"firefox"`, then the emitted `manifest.json` will respect these differences so the extension can be loaded in Firefox. 

There are some parts that don't work very well yet -- in particular, hot module reloading does not work in Firefox because the service worker generated by this extension does not work as a background page.

2023-02-08 17:38 UTC, jacksteamdev requested changes
This looks great! FF support is something people have asked for.

CI doesn't pass yet, I'll be happy to merge this once it does 👍

2023-02-10 04:10 UTC, thilinaaligent commented
for the time being I am using a vite plugin to manually modify the manifest.json. Apart from removing `using_dynamic_url`  I also had to add https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#description  since All [Manifest V3 extensions](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) need an add-on ID in their manifest.json when submitted to AMO.

2023-02-22 10:50 UTC, jhholm commented
I took a quick look at this, as I've been trying to work on porting an extension from Chrome to Firefox. I don't think the linting issues are a big problem, but the bigger issue is that a dev build doesn't work on Firefox. A background page cannot import from localhost because of CSP, and CSP doesn't allow localhost in MV3. @laptou already left a comment about this in the code.

I worked around the dev issue with **vite build --watch --sourcemap** instead of **vite dev**. 

I should be able to provide my view on the small changes to the linting issues if needed.

2023-02-28 12:13 UTC, iPaulPro commented
> for the time being I am using a vite plugin to manually modify the manifest.json. Apart from removing `using_dynamic_url` I also had to add https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#description since All [Manifest V3 extensions](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/) need an add-on ID in their manifest.json when submitted to AMO.

@thilinaaligent Could you possibly share the details of the vite plugin and configuration you're using?

2023-02-28 22:49 UTC, laptou commented
> CI doesn't pass yet, I'll be happy to merge this once it does +1

As mentioned by @jhholm, this PR isn't fully complete because I haven't figured out how to make hot reloading work in Firefox. Background pages have different APIs and capabilities from service workers, so it will require some more work to get this fully baked. I'm not sure when I will get around to writing a background page though, so if anyone else wants to take it on, that would be much appreciated.

2023-03-04 21:17 UTC, kjaonline commented
@laptou wanting to take this on. Can I get some guidance on your idea?

2023-03-25 00:44 UTC, laptou commented
@kjaonline What kind of guidance are you looking for? The main thing that is needed to make this PR complete in my opinion is an implementation of hot reloading that is compatible with Firefox's background pages. This requires looking at how the HMR service worker is implemented for Chrome and addressing the differences between the technologies (which are largely differences in the restrictions on how scripts can be loaded)

2023-08-16 17:07 UTC, laptou commented
@IamFive I've been occupied with other stuff for a while; if you would like to fix the CI stuff it's all yours

2023-08-17 13:52 UTC, winstxnhdw commented
@laptou I just created a PR to this fork that fixes the CI. I didn't attempt to fix the HMR issue because that isn't really important to me. Let's just get this PR merged first.

2023-09-24 22:00 UTC, jacksteamdev commented
Closing in favor of #776 Thanks for putting this together!

2023-09-24 22:00 UTC, closed without merging

2023-09-25 12:04 UTC, jacksteamdev commented
Firefox support has landed on NPM https://www.npmjs.com/package/@crxjs/vite-plugin/v/2.0.0-beta.19