plugin output should regard to config.root
crxjs/chrome-extension-tools pull request #759
Opened 2023-07-25 11:07 UTC by intellild

2024-01-14 19:20 UTC, jacksteamdev requested changes
The fix itself looks good to me, thanks for the contribution. We can merge after the following are completed.

## Tasks before merging
- [ ] Verify that it works on Windows
- [ ] Add an e2e test

2024-01-14 19:20 UTC, jacksteamdev commented on packages/vite-plugin/src/node/fileWriter.ts
> +import path from 'path'
@intellild Have you tested this on Windows? IIRC, we need to use `node:path/posix` here for Windows compatibility.

2024-06-28 07:08 UTC, intellild commented
Sorry for the late, migrated to posix path

2025-02-04 16:18 UTC, jacksteamdev commented
Thank you for your contribution to CRXJS! I'm closing this PR since it's been open for more than 90 days without completing the requested changes (add e2e test).

2025-02-04 16:18 UTC, closed without merging